theme: jekyll-theme-minimal

# Site settings
title: Liyang's Blog(你博客的标题)                     #你博客的标题
SEOTitle: You 你的博客 | You Blog (显示在浏览器上搜索的时候显示的标题)        #显示在浏览器上搜索的时候显示的标题
header-img: 15541562164299_.pic_hd.jpg     #显示在首页的背景图片
email: You@gmail.com    
description: "You Blog"              #网站介绍
keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone" #关键词
url: "https://qiubaiying.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "说点装逼的话。。。"
sidebar-avatar: 15541562164299_.pic_hd.jpg      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g

# SNS settings
RSS: false
weibo_username:     秃头少年诸葛菊香
zhihu_username:     username
github_username:    username
facebook_username:  username
jianshu_username:   jianshu_id
